### ISSUE TITLE
A to-do list

### ISSUE THREAD

**Issue by SketchySketch** [412LEGEND/Homepage#1]
- [x] Create a website

- [x] Add some content

- [x] make an animation

- [x]  beautify it!

- [x] Simplify adding contents

- [x] Add “quotes”

- [x] Add “our stories”

- [x] ...

**Comment by SketchySketch** [comment]
Well done!
